/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddAlarm: typeof import('./src/components/Authenticated/AddAlarm.vue')['default']
    AlarmList: typeof import('./src/components/Authenticated/AlarmList.vue')['default']
    AppAuthenticated: typeof import('./src/components/AppAuthenticated.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppSettings: typeof import('./src/components/AppSettings.vue')['default']
    AppSignin: typeof import('./src/components/AppSignin.vue')['default']
    AppSnackbar: typeof import('./src/components/AppSnackbar.vue')['default']
    AppToolbar: typeof import('./src/components/AppToolbar.vue')['default']
    LightControl: typeof import('./src/components/Authenticated/LightControl.vue')['default']
    PiInfo: typeof import('./src/components/Settings/PiInfo.vue')['default']
    PiIp: typeof import('./src/components/Settings/PiIp.vue')['default']
    PiRestart: typeof import('./src/components/Settings/PiRestart.vue')['default']
    PiUptime: typeof import('./src/components/Settings/PiUptime.vue')['default']
    RefreshData: typeof import('./src/components/Settings/RefreshData.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignOut: typeof import('./src/components/Settings/SignOut.vue')['default']
    StatusRow: typeof import('./src/components/Toolbar/StatusRow.vue')['default']
    TimeZone: typeof import('./src/components/Settings/TimeZone.vue')['default']
  }
}
